# SPDX-License-Identifier: MIT
---
- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

# Examples of some tasks:
- name: Ensure required packages are installed
  package:
    name: "{{ __aide_packages }}"
    state: present
    use: "{{ (__aide_is_ostree | d(false)) |
             ternary('ansible.posix.rhel_rpm_ostree', omit) }}"

- name: Ensure required services are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ __aide_services }}"

- name: Generate /etc/{{ __aide_foo_config }}
  template:
    src: "{{ __aide_foo_config }}.j2"
    dest: /etc/{{ __aide_foo_config }}
    backup: true
    mode: "0400"
  notify: Handler for aide to restart services
