# SPDX-License-Identifier: MIT
---
- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

# Examples of some tasks:
- name: Ensure required packages are installed
  ansible.builtin.package:
    name: "{{ __aide_packages }}"
    state: present
    use: "{{ (__aide_is_ostree | d(false)) |
             ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
  when:
    - aide_install

- name: Ensure required services are enabled and started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ __aide_services }}"

- name: Generate "/etc/{{ __aide_config }}"
  ansible.builtin.template:
#    remote_src: true
    src: "{{ aide_custom_template }}"
    dest: "/etc/{{ __aide_config }}"
    mode: "0400"
  when:
    - aide_custom_template

#- name: Print Header
#  ansible.builtin.shell: head /etc/aide.conf || true

- name: Initialize AIDE database
  when:
    - aide_init
  block:
    - name: Initialize AIDE database
      ansible.builtin.command:
        cmd: aide --init
      changed_when: true

    - name: Copy AIDE reference database
      ansible.builtin.copy:
        remote_src: true
        src:  "{{ __aide_db_new_name }}"
        dest: "{{ __aide_db_name }}"
        owner: root
        group: root
        mode: "0440"
        force: yes
      when:
        - not aide_fetch_db

    - name: Remove remote AIDE database file
      ansible.builtin.file:
        path: "{{ __aide_db_new_name }}"
        state: absent
      when:
        - not aide_fetch_db

- name: Fetch AIDE database
  when:
    - aide_fetch_db
  block:
    - name: Fetch AIDE database
      ansible.builtin.fetch:
        src: "{{ __aide_db_new_name }}"
        dest: "{{ aide_db_fetch_dir }}"

    - name: Remove remote AIDE database file
      ansible.builtin.file:
        path: "{{ __aide_db_new_name }}"
        state: absent

- name: Check AIDE integrity
  when:
    - aide_check
  block:
    - name: Copy AIDE reference database
      ansible.builtin.copy:
        src: "{{ aide_db_fetch_dir }}/{{ inventory_hostname }}\
        {{ __aide_db_new_name }}"
        dest: "{{ __aide_db_name }}"
        owner: root
        group: root
        mode: "0440"
      when:
        - aide_fetch_db

    - name: Check against AIDE reference database
      ansible.builtin.command:
        cmd: aide --check
      changed_when: true

- name: Update AIDE database and fetch it
  when:
    - aide_update
  block:
    - name: Update AIDE database
      ansible.builtin.command:
        cmd: aide --update
      register: __aide_update_result
      failed_when: "'AIDE found NO differences between database and filesystem. Looks okay!!'\
      not in __aide_update_result.stdout"
      changed_when: true

    - name: Fetch AIDE database
      ansible.builtin.fetch:
        src: "{{ __aide_db_new_name }}"
        dest: "{{ aide_db_fetch_dir }}"

    - name: Remove remote AIDE database file
      ansible.builtin.file:
        path: "{{ __aide_db_new_name }}"
        state: absent
