# SPDX-License-Identifier: MIT
---
- name: Example aide role invocation
  hosts: targets
  tasks:
    - name: Include role aide
      vars:
        aide_custom_template: /tmp/aide-custom.conf.j2
        aide_db_fetch_dir: files
        aide_install: true
        aide_init: true
        aide_fetch_db: true
        aide_check: true
        aide_update: true
      ansible.builtin.include_role:
        name: linux-system-roles.aide
